import "./index.css";
import "./app.css";
import Image from "next/image";
import Link from "next/link";

//import './globals.css'
import { Inter } from "next/font/google";
import { HelloWorld } from "@/components/HelloWorld";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div id="root">
          <header>
            <Image
              alt="Next logo"
              className="logo"
              src={"/next.svg"}
              width="120"
              height="120"
            />
            <div className="wrapper">
              <HelloWorld msg="Welcome to Web3!"></HelloWorld>
              <nav>
                <Link href={"/"}>Home</Link>
                <Link href={"/about"}>About</Link>
                {/* <RouterLink to="/">Home</RouterLink> */}
                {/* <RouterLink to="/about">About</RouterLink> */}
              </nav>
            </div>
          </header>
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
